server:
    port: 8081

spring:
    application:
        name: employee-service
    datasource:
        url: jdbc:mysql://localhost:3306/employeeDB?useSSL=false&serverTimeZone=UTC&useLegacyDatetimeCode=false
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            format_sql: true
            default_schema: employeeDB
    
    config:
        import: "optional:configserver:http://localhost:9002"
    cloud:
        config:
            name: employee
            discovery:
                enable: true
                service-id: cofig-server

eureka:
    client:
        service-url:
           defaultZone: http://localhost:9001/eureka/
            #defaultZone: ${EUREKA_URI:http://localhost:9001/myeureka/eureka}
    instance:
            preferIpAddress: true